[package]
name = "todorust"
version = "0.1.0"
authors = ["adeyahya <adeyahyaprasetyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "^0.8"
rusqlite = "0.21.0"